### ISSUE TITLE
Option to put the code outline to the left of the editor pane as well?

### ISSUE THREAD

**Issue by sandgorgon** [Chris2011/nb-codeoutline#15]
Hello Benno,

Would it be possible to make the position of the code outline configurable (left or right)? 

Thanks for the plugin.

Regards.

**Comment by markiewb** [comment]
I will see, what I can do. But I am not sure, if it can be done dynamically. I have never seen switching sides at runtime in other plugins nor in the IDE itself

**Comment by sandgorgon** [comment]
I would think it need not be dynamic. But an option to set maybe at start or restart of the IDE. Thanks for considering it.  Regards.

**Comment by markiewb** [comment]
Fixed in 1.2.0
