### ISSUE TITLE
Add mnemonic to menu entry

### ISSUE THREAD

**Issue by nmatt** [Chris2011/nb-codeoutline#23]
Please add a keyboard shortcut to the menu entri in the "View" menu.

**Comment by markiewb** [comment]
IMO toggling is seldom used, so why? You can already define one using the options. 

![2016-01-07_20h54_51](https://cloud.githubusercontent.com/assets/1857095/12181168/eb1c91f8-b580-11e5-8d4b-5d96b8311e6b.png)

I will at least add a mnemonic to the menu entry

**Comment by markiewb** [comment]
Try `ALT-V, ALT-U`

**Comment by nmatt** [comment]
Thanks, works perfectly! By "keyboard shortcut", I meant only the mnemonic in the menu. It's nice to be able to quickly use the menu command by keyboard and not have to allocate (and remember) a global keyboard shortcut.

Toggling is useful when you temporarily dock other windows at the side of the editor, or when you frequently work with different screen resolutions (remote desktop), and with small screen resolutions where you don't want to show the code outline permanently.
