### ISSUE TITLE
Add a right bar used to toggle on/off the bookmarks

### ISSUE THREAD

**Issue by Git-GT** [Chris2011/nb-codeoutline#28]
Hi, great add-on.
I would like to suggest you an enhancement that is a bit unrelated to this addon but that maybe could be integrated on it.

Currently when I want to bookmark a line of code I use a breakpoint because the breakpoint toggle mechanism is very fast, it is sufficient to click left border in corrispondence of the line. 
I would like to have the same feature for the toggle of the bookmarks but the left bar is yet  used for the breakpoints, what do you think to add a small right bar clicking on which is possible to toggle on/of a bookmark in the corresponding line?
Thanks in any case,
best regards
## 

Giuseppe Tino

**Comment by markiewb** [comment]
I will try to create a separate plugin. See https://github.com/markiewb/nb-bookmarks-sidebar/issues/1
