### ISSUE TITLE
Support for NB 8.2

### ISSUE THREAD

**Issue by eransharpe** [Chris2011/nb-codeoutline#31]
Thanks for the awesome plugin!
Unfortunately it is not supported in Netbeans September 2016 Release.

(Using Mac OS Sierra)
I installed it manually through tools->plugins->downloaded and selected the package that I got from this page: http://plugins.netbeans.org/plugin/57219
It got installed successfully and the menu view->show outline is selected
but the outline doesn't appear like it did in Netbeans 8.1

**Comment by markiewb** [comment]
Thanks for the issue. I will upload all my plugins for 8.2 soon! In the meantime use the 8.1 update center instead - see https://benkiew.wordpress.com/2016/09/18/missing-plugins-for-your-netbeans-nightly-builds/

**Comment by not-surt** [comment]
So is this meant to be working for 8.2 now?
I've tried both the pending 8.2 version and the 8.1 version, the "Show Outline" option appears in the view menu but the outline never appears in the editor.

**Comment by Wirone** [comment]
Same for me, I have stable Netbeans 8.2 (Build 201609300101) + Code Outline v1.3.1 (installed from update center) and outline is not available (menu options exists, checked `View > Show outline`).

**Comment by markiewb** [comment]
Fixed in 1.3.2. I put a new version to the 8.2 update center. Wait for the verification and the update will be downloaded automatically by your NB IDE.

**Comment by Wirone** [comment]
Thank you very much! I've installed from `nbm` file and it works properly :-)
