### ISSUE TITLE
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module 

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-codeoutline#33]
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module de.markiewb.netbeans.plugins.codeoutline: added = [module org.openide.util.ui > 9.3, module org.openide.filesystems.nb, module org.openide.filesystems.compat8, module org.netbeans.modules.editor.document > 1.0] removed = []; details: [#243100: Separate desktop-independent utilities, Separation of Parsing and Indexing APIs, Separation of desktop and cleanup]

Since 8.2

**Comment by Chris2011** [comment]
NB 8.2 is not supported anymore. Latest plugin is working for NB 23 https://github.com/Chris2011/nb-codeoutline/releases/tag/1.4.0
