### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by AntonioCS** [Chris2011/nb-codeoutline#39]
I put two files side by side to compare but I had the minimap in the middle and I just couldn't disable it.
Is there any option somewhere?

**Comment by markiewb** [comment]
There is an option in the `View` main menu.

Also try the other better maintained plugin - http://plugins.netbeans.org/plugin/71031/minimap

**Comment by Chris2011** [comment]
It is better maintained maybe, but not as better as yours ;)
