### ISSUE TITLE
NetBeans 11 - not Working

### ISSUE THREAD

**Issue by mrhyper** [Chris2011/nb-codeoutline#41]
In Netbeans 11.0
The Outline window doesn't open.
There is the Code Outline TAB in options but nothing happenes.

A fix would be nice - I love this plugin .. NB11 is much faster I think so it would be nice to have  Code Outline working again

**Comment by Chris2011** [comment]
Not working in NB 11 but working again in NB 23. Please upgrade and install latest version of this plugin which is https://github.com/Chris2011/nb-codeoutline/releases/tag/1.4.0
