### ISSUE TITLE
Support dark themes like Dark Metal

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-codeoutline#8]
ACTUAL: black text on white background.
EXPECTED: white text on dark background.

**Comment by Chris2011** [comment]
A thing, what I would prefer is to set the outline view as an little overlay directly into the editor before the scrollbar, without having a separation. This is was Sublime Text 2 has: http://www.bit-101.com/blog/wp-content/uploads/2012/05/Screenshot-Documents-Playing-With-Chaos-Book-book-pwc_ch01.html-playing_with_chaos-Sublime-Text-2.png So maybe you can inherit the background or do a opacity for this, And it's a bit inconspicuous than now.

Regards

Chris

**Comment by markiewb** [comment]
I am sorry. AFAIK it is not possible to embed the view into the editor.
Neither the code outline plugins for Eclipse/IDEA do this.

Eclipse:
http://marketplace.eclipse.org/sites/default/files/styles/ds_solution_screenshot/public/overview_6.png?itok=Bv5c8K6G
Idea: http://plugins.jetbrains.com/files/6274/screenshot_14688.png

My plan is to use the use the background color of the editor. But the
outline cannot be placed at the left of the editor scrollbar

With kind regards, markiewb

2015-02-05 8:58 GMT+01:00 Chris2011 notifications@github.com:

**Comment by Chris2011** [comment]
Is it not possible to do that like in HTML? I don't know java with swing good enough but I thought the editor has position relative (as a div in html) and the outline has position absolute and has top: 0 and right: 0 (like a div inside the relative div in html). Isn't it possible? Because of the swing components?

**Comment by thiagolucio** [comment]
I have a similar question to Chris2011.  Which file i change de color apparence config this plugin? Which is the path to this file?

**Comment by markiewb** [comment]
@Thiago: Sorry. There is no setting yet. Currently it is hardcoded. The
next version will use the colors from the Colors&Fonts options

Best regards, markiewb

**Comment by thiagolucio** [comment]
Thanks :)

**Comment by istvan-ujjmeszaros** [comment]
Would be great if we could configure the colors.

**Comment by p2rkw** [comment]
I'm using dark theme, but in code outline both text and background are white (light grey).
If values are hardcoded why background colour is white? What is source of colours?
I don't have theme named "default", should I create one?

added:
If you hardcode you should hardcode both values, not only background color.

netbeans dev 04-06-2015
code outline 1.2.0

**Comment by luislobo** [comment]
Hi, great job with this plugin. Can you please merge your fix for dark background? thank you!

**Comment by markiewb** [comment]
![2016-01-04_23h46_58](https://cloud.githubusercontent.com/assets/1857095/12102993/2ff6b68a-b33f-11e5-9813-7766fe1de5b6.png)

![2016-01-04_23h44_17](https://cloud.githubusercontent.com/assets/1857095/12103002/402d787c-b33f-11e5-8dd0-2eaa87d6a8ca.png)

fixed in 1.3.0
